### ISSUE TITLE
Automated release

### ISSUE THREAD

**Issue by judoole** [bekkopen/NoCommons#21]
Opinion: `mvn release:prepare release:perform` on developer machines are too cumbersome and way too easy to forget how-to. We should implement a way to just either tag master or have commits to master deploy a new version to Maven Central or Sonatype.

Guardian seems to have solved this for Travis http://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

**Comment by steinim** [comment]
I totally agree! I think I have gotten past the release-plugin cumbersomeness, but I am struggling with the site-plugin. Commenting it out.

**Comment by judoole** [comment]
@steinim Maybe because you're using Java 8? site-plugin I mean. I ran into some issues there.

**Comment by steinim** [comment]
I switched to Java 7 after noticing that ;)

**Comment by steinim** [comment]
I was finally able to release :)

**Comment by olemartin** [comment]
:+1:  :-)

**Comment by steinim** [comment]
Didn't mean to close it. We should find a better way to do releases.

**Comment by eivinhb** [comment]
@rultor hello

**Comment by eivinhb** [comment]
@rultor release, tag is `0.8.2`

**Comment by eivinhb** [comment]
@rultor release, tag is 0.8.2

**Comment by eivinhb** [comment]
@rultor release, tag is 0.8.2

**Comment by eivinhb** [comment]
@rultor release, tag is 0.8.2

**Comment by eivinhb** [comment]
@rultor release, tag is 0.8.2

**Comment by eivinhb** [comment]
@rultor release, tag is 0.8.2

**Comment by eivinhb** [comment]
ok da. @rultor release, tag=`0.8.2`

**Comment by eivinhb** [comment]
@rultor release, tag=`0.8.2`

**Comment by eivinhb** [comment]
@rultor release, tag=`0.8.2`

**Comment by eivinhb** [comment]
@rultor release, tag=`0.8.2`

**Comment by judoole** [comment]
Just sit back and wait until [Github Actions](https://github.com/features/actions) becomes public, and this will all be just a bad memory.

**Comment by eivinhb** [comment]
@rultor release, tag=0.9.0

**Comment by eivinhb** [comment]
@rultor release, tag=`0.9.0`

**Comment by eivinhb** [comment]
https://repo1.maven.org/maven2/no/bekk/bekkopen/nocommons/0.9.0/ <- automatisk release fungerer nå
