### ISSUE TITLE
Funksjonalitet rundt telefonnummer mangler

### ISSUE THREAD

**Issue by jgogstad** [bekkopen/NoCommons#22]
README.md nevner funksjonalitet knyttet til telefonnummer, dette eksisterer hverken på `master` eller `0.6`

**Comment by judoole** [comment]
Hmmm. Husker jeg ukritisk klipp-limte inn README.md fra https://github.com/bekkopen/NoCommons/wiki/NoCommons. I likhet med deg, så finner ikke jeg heller noe kode relatert til telefonnummer. Kanskje @steinim husker hvor teksten opprinnelig kommer fra?

**Comment by steinim** [comment]
Det har jeg dessverre ikke peiling på. Kan ikke huske noe om telefonnummer og lagde vel aldri en eneste branch på dette prosjektet. Jeg konverterte det fra svn til git og det som har skjedd siden har jeg ingen kontroll på.

**Comment by judoole** [comment]
Kanskje noen hovedkontributerne som forsvant fra historikken husker noe @pekrimen @eivindw ?

**Comment by johnkors** [comment]
Kanskje uansett mer interessant å høre hva rundt telefonnummer som kunne vært greit å ha med?

**Comment by judoole** [comment]
@johnkors Ifølge copy-pasten i README.md så var det dette. 

* Telefonnummer
  * Gyldig nummer (mange er reserverte)
  * "Korrekte" skrivemåter
  * Diverse logikk rundt nummerserier - finn leverandør, fylke etc
 [http://www.npt.no/portal/page?_pageid=121,47706,121_47719&_dad=web&_schema=PORTAL](http://www.npt.no/portal/page?_pageid=121,47706,121_47719&_dad=web&_schema=PORTAL])

Linken er temmelig død, så hvordan vet jeg ikke hvordan. Godt mulig denslags ikke er aktuelt i dag.

**Comment by kvangaball** [comment]
Jeg har skrevet litt om på readme.
