### ISSUE TITLE
KidnummerValidator tar ikke høyde for bindestrek/minustegn på slutten

### ISSUE THREAD

**Issue by emilmork** [bekkopen/NoCommons#25]
KidnummerValidator tar ikke høyde for "-" på slutten av kid-nummeret.

Liten obs på at kidnummer kan inneholde "-" på slutten og da ikke nødvendigvis kun et tall med lengde mellom 2 og 25 tegn.

Dette er på grunn av bruk av hvis man bruker mod11 kan tallet 10 forekomme og erstattes med "-" fordi checksummet kun skal være ett tegn.

Kilde: [Statens innkrevningssentral](https://www.sismo.no/no/pub/sporsmalOgSvar/Generelle%20s&s/kid-feil)

[OCRGiro](https://www.nets.eu/no-nb/PublishingImages/Lists/Accordion%20%20OCR%20giro/AllItems/OCR%20giro%20Brukerh%C3%A5ndbok.pdf)

**Comment by olemartin** [comment]
Strålende med en pull-request som fikser feilen ;-)

**Comment by emilmork** [comment]
Ja det var det. Jeg har ikke java-miljø satt opp så det blir nok ikke, men jeg kan poste hvordan vi kommer til å løse det for .NET. Postet samme info på .NET versjonen av dette repoet :)

**Comment by eivinhb** [comment]
Jeg forsøkte også å generere en KID som har `-` i seg og DnB nekter bruk av dette. 

![image](https://user-images.githubusercontent.com/383121/49895611-29afe700-fe51-11e8-885e-b3b12676da6e.png)

Jeg har laget en fiks som gjør at NoCommons validerer korrekt ihht. til NETs sine retningslinjer. Men det er viktig at utviklere selv er kritiske til bruk av disse KID-ene. Det er dårlig UX og jeg vedder på at det ikke bare er DnB som nekter slike KID-er.
