### ISSUE TITLE
Fødselsnummer og D-nummer

### ISSUE THREAD

**Issue by LemmingAvalanche** [bekkopen/NoCommons#37]
`no.bekk.bekkopen.person.Fodselsnummer` tar høyde for at et `Fodselsnummer` kan være et D-nummer.  Sjekksjummen funker selvsagt i validatoren (`FodselsnummerValidator`) og metoder som `getDayInMonth()` passer på å ta trekke 4 fra det første tallet i strengen hvis det et D-nummer.  Det hadde kanskje vært greit å nevne i Javadoc til klassen (samt de andre relaterte klassene) at et D-nummer er et gyldig `Fodselsnummer`, altså at ikke kun ordinære fødselsnummer vil bli godkjent.

**Comment by eivinhb** [comment]
Ja, dnr er 100% gyldige fødselsnummer.
Legger til litt dok i https://github.com/bekkopen/NoCommons/pull/39 
Merk at med syntetiske fødselsnummer som innføres nå i disse dager så er det IKKE gyldige fødselsnummer, med mindre vi flagger at vi øsnker at de skal være det.

**Comment by LemmingAvalanche** [comment]
Takk!
