### ISSUE TITLE
Oppdatering av regler for D-nummer høsten 2021

### ISSUE THREAD

**Issue by eloekset** [bekkopen/NoCommons#54]
Testene for D-nummer bør oppdateres for å sjekke de nye D-nummerne som ble satt i produksjon 16. november 2021.

Referanse til dokumentasjon hos skatteetaten: https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/sporsmal-og-svar/

https://github.com/bekkopen/NoCommons/blob/f642b77a097be976e24856fa6a6c01096e8b69c7/src/test/java/no/bekk/bekkopen/person/FodselsnummerTest.java#L122

**Comment by eloekset** [comment]
`testIsDNumber()` er uberørt av endringene, men det kan se ut til at metoden `getCentury()` må oppdateres for områdene

- 200-499
- 600-999

**Comment by eivinhb** [comment]
Vi fikser det her: https://github.com/bekkopen/NoCommons/pull/55
