### ISSUE TITLE
Støtte for helsesektorens testidenter med +65 på måned. 

### ISSUE THREAD

**Issue by arakvaag** [bekkopen/NoCommons#57]
Det er allerede støtte i dette biblioteket for testidenter fra Skatteetaten, de som har +80 på måned, som er veldig bra. Innenfor helsesektoren (gjennom Norsk Helsenetts Persontjenesten) er det på veg inn et annet sett testidenter, hvor det i stedet legges til 65 på måned. Mer om dette her: https://www.nhn.no/tjenester/persontjenesten/systemleverandorer-kom-i-gang/test-og-testmiljo, i kapittelet Testdata.

Slike testidenter med +65 på måned vil kun bli brukt i helsesektoren, altså ikke hos alle som er nedstrøms fra Skatts Folkeregister. Det blir likevel en stor mengde applikasjoner som vil trenge å støtte +65-identene i sine testmiljøer. 

Jeg jobber med en løsning i helsesektoren, og bruker i dag NoCommons-biblioteket. Det ville vært en stor fordel for oss om vi unngikk å skrive logikk rundt NoCommons-koden for å håndtere +65-identer, eller i verste fall måtte fjerne NoCommons fra vår kodebase. Jeg tar for gitt at denne problemstillingen gjelder mange andre løsninger også. 

Er det aktuelt å legge inn støtte for disse testidentene? 

Det kan være jeg, eller andre hos oss, kan bidra med en pull request, men fint å vite om dette er noe som vil bli akseptert som del av NoCommons sin funksjonalitet før vi starter et evt. arbeid på det.

**Comment by eivinhb** [comment]
Dette var nytt for meg. Ja, det må vi kunne få til. Det burde være ganske kurrant å lage noe ala det vi gjør for dagens syntestiske brukere. Der har vi en feature-toggle for å slå valideringen av og på avhengig av miljø. Vi kan egentlig bare gjøre noe av akkurat det samme. Om du har lyst/tid til å lage en PR, så er det veldig velkomment.

**Comment by arakvaag** [comment]
Så bra, da skal vi sette oss inn i koden, også håper jeg vi kan få til en PR snart.

**Comment by arakvaag** [comment]
Vi trenger en avklaring på https://github.com/bekkopen/NoCommons/issues/58 før vi fortsetter vårt arbeid med å lage en PR her.

**Comment by eivinhb** [comment]
Da er vel avklaringen tatt. Releaset 0.14.0.

**Comment by Asgeiraan** [comment]
Supert!
Jeg har vært i samtale med @arakvaag;
Da begynner jeg å integrere støtte for testidenter med +65 på måned.

**Comment by Asgeiraan** [comment]
Da har jeg opprettet en PR på:
https://github.com/bekkopen/NoCommons/pull/66

**Comment by eivinhb** [comment]
Siden lenken nevnt over er død, legger jeg denne nye her: https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/test-og-testmiljoe/ "Testdata"

**Comment by eivinhb** [comment]
Releaset #0.15.0
