### ISSUE TITLE
Fjerne/erstatte avhengighet til javax.validation

### ISSUE THREAD

**Issue by arakvaag** [bekkopen/NoCommons#58]
NoCommons har en avhengighet til javax.validation - validation-api. Siste versjon av dette biblioteket er fra desember 2017, og er del av Java EE (javax-namespacet). Nå har jakarta-namespacet tatt over, også for validation-api.

Vi synes det er uheldig at NoCommons drar inn en gammel Java EE-avhengighet inn i våre applikasjoner. Vi tenker at det kanskje er en god ide å bygge om slik at bruken av denne validation-api fjernes, selv om vi forstår at det er en større endring. Om det er ønskelig å beholde API-et er det vel da viktig å få oppgradert til jakarta-namespacet. 

Kan dere si noe om deres vurdering av problemet, og om dere ser mulighet for at det blir gjort oppgradering av biblioteket som løser det?

**Comment by eivinhb** [comment]
Det vel egentlig ikke noe problem å oppgradere til hibernate 6 og bruke jakarta. Men siden det er breaking så må vi kanskje lage en ny versjon ala et Jetty har holdt på med en stund. 
Tiden er vel inne for at vi gjør det her også. Jeg ser @janhoy har foreslått å gå over på java 11 https://github.com/bekkopen/NoCommons/pull/61 Kan hende vi kan lage en ny versjon på java 17 (?) og gjøre det totale spranget samtidig.

**Comment by eivinhb** [comment]
@arakvaag For dere, ville det være et problem å lage en ny release med target java 17? ref: diskusjonen her: https://github.com/bekkopen/NoCommons/pull/61

**Comment by eivinhb** [comment]
Når jeg tenker meg om så er det kanskje egentlig ikke noe problem å bytte ut javax.validation med jakarta.validation og fortsatt bruk av java 8. Det er jo en major breaking change. Sånn sett kunne vi kanskje bare releaset 1.0 med jakarta. 
Egentlig hadde jeg håpet at 1.0-releasen gikk på å få java.time inn i stedet for å bruke Calender-apiet som biblioteket bruker i dag.

**Comment by eivinhb** [comment]
Laget denne PR-en:
https://github.com/bekkopen/NoCommons/pull/64

**Comment by eivinhb** [comment]
Releaset [0.14.0](https://github.com/bekkopen/NoCommons/releases/tag/0.14.0)
