### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by janhoy** [bekkopen/NoCommons#62]
In pom.xml you claim that the software is Apache 2.0 licensed.
But in LICENSE you say it is MIT.
Choose one :)

**Comment by eivinhb** [comment]
Godt sett. Det er nok bare oversett av de som la inn MIT. Jeg kan ta en runde på det.

**Comment by eivinhb** [comment]
Ta en titt på denne: https://github.com/bekkopen/NoCommons/pull/65
